version: '3.4'

services:
  keycloak:
    platform: linux/x86_64
    build: 
      context: services/keycloak
    command:
      - start-dev
      - --http-port=2380
      - --http-relative-path=/auth
      - --import-realm
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "2380:2380"
    networks:
      - ax
  gateway-db:
    image: bitnami/etcd:3.5.7
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://gateway-db:2379
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 5s
      timeout: 10s
      retries: 6
    networks:
      - ax
  gateway:
    platform: linux/x86_64
    build:
      context: services/gateway
    environment:
      - APISIX_DEPLOYMENT_ETCD_HOST=["http://gateway-db:2379"]
      - BANK_APP_HOST=httpgobin
      - BANK_APP_PORT=8080
    ports:
      - 2290:9000
      - 9080:9080
      - 9180:9180
      - 9443:9443
      - 9090:9092
      - 9100:9100
    depends_on:
      gateway-db:
        condition: service_healthy
      grafana-loki:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "cat", "/home/apisix/routes-loaded"]
      interval: 30s
      timeout: 10s
      retries: 30
    networks:
      - ax
  gateway-dashboard:
    platform: linux/x86_64
    build:
      context: services/gateway-dashboard
    ports:
      - 9000:9000
    depends_on:
      gateway-db:
        condition: service_healthy
    networks:
      - ax
  httpgobin:
    build:
      context: services/microservice
    ports:
      - 3380:8080
    networks:
      - ax
  httpbin:
    image: kennethreitz/httpbin
    ports:
      - 2280:80
    networks:
      - ax
  grafana:
    build: 
      context: services/grafana
    ports:
      - 3000:3000
    depends_on:
      grafana-loki:
        condition: service_healthy
    networks:
      - ax
  grafana-loki:
    build: 
      context: services/grafana-loki
    ports:
      - 3100:3100
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://grafana-loki:3100/ready"]
      interval: 5s
      timeout: 10s
      retries: 6
    networks:
      - ax
  prometheus:
    build:
      context: services/prometheus
    depends_on:
      gateway:
        condition: service_healthy
    networks:
      - ax
networks:
  ax:
    driver: bridge