version: '3.4'

services:
  keycloak:
    profiles: [ "idp" ]
    platform: linux/x86_64
    build: 
      context: services/keycloak
    command:
      - start-dev
      - --http-port=2380
      - --http-relative-path=/auth
      - --import-realm
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "2380:2380"
    networks:
      - ax

  apisix-gateway:
    profiles: [ "apisix-standalone" ]
    platform: linux/x86_64
    build:
      context: services/apisix-gateway
    ports:
      - 9081:9080
    depends_on:
      grafana-loki:
        condition: service_healthy
    networks:
      - ax

  gateway-db:
    profiles: [ "apisix" ]
    image: bitnami/etcd:3.5.7
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://gateway-db:2379
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 5s
      timeout: 10s
      retries: 6
    networks:
      - ax

  gateway:
    profiles: [ "apisix" ]
    platform: linux/x86_64
    build:
      context: services/gateway
    environment:
      - APISIX_DEPLOYMENT_ETCD_HOST=["http://gateway-db:2379"]
      - BANK_APP_HOST=httpgobin
      - BANK_APP_PORT=8080
    ports:
      - 2290:9000
      - 9080:9080
      - 9180:9180
      - 9443:9443
      - 9090:9092
      - 9100:9100
    depends_on:
      gateway-db:
        condition: service_healthy
      grafana-loki:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "cat", "/home/apisix/routes-loaded"]
      interval: 30s
      timeout: 10s
      retries: 30
    networks:
      - ax

  gateway-dashboard:
    profiles: [ "apisix" ]
    platform: linux/x86_64
    build:
      context: services/gateway-dashboard
    ports:
      - 9000:9000
    depends_on:
      gateway-db:
        condition: service_healthy
    networks:
      - ax

  httpgobin:
    profiles: [ "apisix", "apisix-standalone", "kong", "kong-standalone" ]
    build:
      context: services/microservice
    ports:
      - 3380:8080
    networks:
      - ax

  grafana:
    profiles: [ "monitoring", "logging" ]
    build: 
      context: services/grafana
    ports:
      - 3000:3000
    depends_on:
      grafana-loki:
        condition: service_healthy
    networks:
      - ax

  grafana-loki:
    profiles: [ "monitoring", "logging" ]
    build: 
      context: services/grafana-loki
    ports:
      - 3100:3100
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://grafana-loki:3100/ready"]
      interval: 5s
      timeout: 10s
      retries: 6
    networks:
      - ax

  prometheus:
    profiles: [ "monitoring", "logging" ]
    build:
      context: services/prometheus
    depends_on:
      gateway:
        condition: service_healthy
    networks:
      - ax

  # kong-db:
  #   image: postgres:9.5
  #   profiles: [ "kong" ]
  #   environment:
  #     POSTGRES_DB: ${KONG_PG_DATABASE:-kong}
  #     POSTGRES_USER: ${KONG_PG_USER:-kong}
  #     POSTGRES_PASSWORD: ${KONG_PG_PASS:-kong}
  #   healthcheck:
  #     test:
  #       ["CMD", "pg_isready", "-d", "${KONG_PG_DATABASE:-kong}", "-U", "${KONG_PG_USER:-kong}"]
  #     interval: 30s
  #     timeout: 30s
  #     retries: 3
  #   networks:
  #     - ax

  kong-gateway:
    profiles: [ "kong-standalone" ]
    build:
      context: services/kong-gateway
    environment:
      KONG_DATABASE: off
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_PROXY_LISTEN: "0.0.0.0:8000"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
      KONG_ADMIN_GUI_LISTEN: "0.0.0.0:8002"
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_DECLARATIVE_CONFIG: "/opt/kong/kong.yaml"
    ports:
      - 8000:8000
      - 8001:8001
      - 8002:8002
    healthcheck:
      test: [ "CMD", "kong", "health" ]
      interval: 10s
      timeout: 10s
      retries: 10
    networks:
      - ax
    
  apisix-etl:
    profiles: [ "apisix", "apisix-standalone" ]
    build:
      context: services/apisix-etl
    networks:
      - ax

  kong-etl:
    profiles: [ "kong-standalone" ]
    build:
      context: services/kong-etl
    networks:
      - ax

networks:
  ax:
    driver: bridge