global_rules:
- id: 1
  plugins:
    tcp-logger:
      _meta:
        disable: false
      batch_max_size: 1
      host: ${ETL_A6_HOST}
      name: tcp logger
      port: ${ETL_A6_PORT}
      tls: false
    prometheus:
      _meta:
        disable: false