services:
- id: {service_id}
  name: "{service_name}-service"
  hosts:
  - "{service_name}.gateway.bank"
  plugins:
    proxy-rewrite:
      regex_uri:
      - "^/anything/(.*)"
      - "/anything/prefixed-$1"
      use_real_request_uri_unsafe: false
  upstream:
      name: "{service_name}"
      type: roundrobin
      hash_on: vars
      scheme: http
      nodes:
      - host: ${{UPSTREAM_HOST}}
        port: ${{UPSTREAM_PORT}}
        weight: 1