global:
  scrape_interval: 1s
  external_labels:
    stack: "apigw"

scrape_configs:
  - job_name: "apisix-gateway-metrics"
    scrape_interval: 15s
    metrics_path: "/apisix/prometheus/metrics"
    static_configs:
      - targets: ["apisix-gateway:9091"]
  - job_name: "apisix-gateway-decoupled-metrics"
    scrape_interval: 15s
    metrics_path: "/apisix/prometheus/metrics"
    static_configs:
      - targets: ["apisix-gateway-decoupled:9091"]
  - job_name: "kong-gateway-metrics"
    scrape_interval: 15s
    metrics_path: "/metrics"
    static_configs:
      - targets: ["kong-gateway:8001"]