global:
  scrape_interval: 1s
  external_labels:
    stack: "apigw"

scrape_configs:
  - job_name: "apisix-gateway-metrics"
    scrape_interval: 15s
    metrics_path: "/apisix/prometheus/metrics"
    static_configs:
      - targets: ["${GW_A6SA_HOST}:${GW_A6SA_METRICS_PORT}"]
  - job_name: "apisix-gateway-decoupled-metrics"
    scrape_interval: 15s
    metrics_path: "/apisix/prometheus/metrics"
    static_configs:
      - targets: ["${GW_A6DC_HOST}:${GW_A6DC_METRICS_PORT}"]
  - job_name: "kong-gateway-metrics"
    scrape_interval: 15s
    metrics_path: "/metrics"
    static_configs:
      - targets: ["${GW_KGSA_HOST}:${GW_KGSA_METRICS_PORT}"]
  - job_name: "kong-gateway-decoupled-metrics"
    scrape_interval: 15s
    metrics_path: "/metrics"
    static_configs:
      - targets: ["${GW_KGDC_HOST}:${GW_KGDC_METRICS_PORT}"]